---
title: "Job Accessibility Regression Analysis"
author: "Transit Equity Team"
date: '2022-06-13'
output:
  pdf_document: default
  html_document: default
---

# Loading data

```{r libraries, message=FALSE}
library(tidyverse)
library(modelr)
library(gt)
```

We begin by loading all of the job accessibility data computed at various thresholds (i.e., what is someone's job accessibility when they're willing to travel via car/transit/transit-with-Red-Line for the stated length of time?).

```{r find-directories}
#setwd('set your directory to /TransitEquity/')
data_dir <- "../processed_data/job_accessibility"
transit_dir <- str_glue("{data_dir}/transit_current")
transit_files <- list.files(transit_dir, pattern = "*.csv")
red_line_dir <- str_glue("{data_dir}/red_line")
red_line_files <- list.files(red_line_dir, pattern = "*.csv")

transit_threshes <- transit_files %>% 
  map_chr(str_remove_all, ".csv") %>% 
  map_dbl(as.double) %>% 
  sort() %>% 
  as_factor()

red_line_threshes <- red_line_files %>% 
  map_chr(str_remove_all, ".csv") %>% 
  map_dbl(as.double) %>% 
  sort() %>% 
  as_factor()
```

```{r load-job-accessibilities}
load_ja <- function(thresh, mode, dir) {
  # This will load a list of job accessibilities from the given directory dir 
  # with the threshold thresh. These values will be tagged with the given 
  # threshold, and mode of transportation.
  read_csv(str_glue("{dir}/{thresh}.csv"), show_col_types = FALSE) %>%
    transmute(FIPS = tract_id, mode = mode,
              threshold = thresh, gravity_sum = gravity)
}

# Load all of the job accessibilities in transit_dir, red_line_dir
transit <- transit_threshes %>%
  map(load_ja, mode = "transit", dir = transit_dir)
red_line <- red_line_threshes %>%
  map(load_ja, mode = "red_line", dir = red_line_dir)

# Join (matching by FIPS) them all into one data frame
all_ja <- bind_rows(transit, red_line) %>% 
  mutate(mode = factor(mode, c("transit", "red_line")))
```

```{r}
service_area <- c("24510280404",
"24510280402",
"24510160500",
"24510280401",
"24510160802",
"24510160801",
"24510200701",
"24510200702",
"24510160700",
"24510160600",
"24510200200",
"24510160400",
"24510160300",
"24510200400",
"24510200100",
"24510160200",
"24510190200",
"24510160100",
"24510190100",
"24510170300",
"24510280600",
"24510180300",
"24510280600",
"24510170100",
"24510040200",
"24510040100",
"24510260501",
"24510030200",
"24510020100",
"24510020300",
"24510260800",
"24510260700",
"24510010200",
"24510030100",
"24510020200",
"24510010500",
"24510260900",
"24510010300",
"24510261100",
"24510220100",
"24510010100")
```

```{r load-svi}
svi <- read_csv("../processed_data/SVI_EP_2020_Standard_Scaled_Summary_Index.csv", 
    col_types = cols_only(FIPS = "d", 
      svi_socioecon_summary = "d"))
all_ja <- svi %>% left_join(all_ja) %>% 
  mutate(disadvantaged = svi_socioecon_summary < 0)
```

```{r}
all_ja <- all_ja %>% pivot_wider(names_from = mode, values_from = gravity_sum) %>% 
  mutate(difference = (red_line - transit) / transit) %>% 
  pivot_longer(c("transit", "red_line", "difference"), names_to = "mode", values_to = "gravity_sum") %>% 
  filter(FIPS %in% service_area)
```

```{r job-accessibility-plots}
ggplot(data = all_ja, mapping = aes(svi_socioecon_summary, gravity_sum)) +
geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", formula = "y ~ x") +
  facet_grid(mode ~ threshold)
```
```{r}
ggplot(data = all_ja, mapping = aes(gravity_sum)) +
  geom_histogram()+
  facet_grid(mode ~ threshold)
```


```{r}
ggplot(data = all_ja %>% filter(threshold == 45, mode %in% c("transit", "red_line")), mapping = aes(x = mode, y = gravity_sum)) +
  geom_boxplot()
```

```{r}
ggplot(data = all_ja %>% filter(threshold == 45, mode %in% c("difference")), mapping = aes(x = gravity_sum)) +
  geom_boxplot()
```

We can also compare our SVI indicator against average travel times.

```{r load-average-travel-time}
transit_time <- read_csv("../processed_data/transit_time_data.csv")
job_flows <- read_csv("../processed_data/job_flows_tract.csv", 
                      show_col_types = FALSE)

transit_time <- transit_time %>%
  left_join(job_flows, 
            by = c("origin" = "h_geocode", 
                   "dest" = "w_geocode")) %>% 
  mutate(job_totals = replace_na(job_totals, 0))

transit_time <- transit_time %>% 
group_by(origin) %>% 
  mutate(
    flow_proportion = job_totals / sum(job_totals)) %>%
  summarize(
    transit = sum(transit_time_current * flow_proportion),
    red_line = sum(transit_time_with_red_line * flow_proportion)) %>%
  mutate(difference = red_line - transit) %>% 
  pivot_longer(c("transit", "red_line", "difference"), names_to = "mode", 
               values_to = "average_transit_time")
transit_time <- svi %>% inner_join(transit_time, by = c("FIPS" = "origin")) %>% 
mutate(disadvantaged = svi_socioecon_summary < 0) %>% 
  filter(FIPS %in% service_area)
```

```{r transit-time-plots}
ggplot(data = transit_time, 
     mapping = aes(svi_socioecon_summary, average_transit_time)) +
  geom_point(alpha = 0.4) +
geom_smooth(method = "lm", formula = "y ~ x") +
  facet_grid(. ~ mode)
```
```{r}
ggplot(data = transit_time %>% filter(mode == "difference"), mapping = aes(x = disadvantaged, y = average_transit_time)) +
  geom_boxplot()
```

```{r}

td_lm = lm(average_transit_time ~ svi_socioecon_summary + mode, 
              data = transit_time %>% filter(mode %in% c("red_line", "transit")))
summary(td_lm)
td_lm = lm(average_transit_time ~ svi_socioecon_summary, 
              data = transit_time %>% filter(mode %in% c("red_line")))
summary(td_lm)
td_lm = lm(average_transit_time ~ svi_socioecon_summary, 
              data = transit_time %>% filter(mode %in% c("transit")))
summary(td_lm)
```
```{r}
td_lm = lm(average_transit_time ~ svi_socioecon_summary * mode, 
              data = transit_time %>% filter(mode %in% c("red_line", "transit")))
summary(td_lm)
```

